server:
  port: 5222
  
#server:
#  port: 5333

#server:
#  port: 5444

#server:
#  port: 5555

spring:
  application:
    name: DONOR-MS 
    
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/rest_jpa_db
      username: root
      password: root
      
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update



